Controllers/MusicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project2016.DAO;
using Project2016.Models;

namespace Project2016.Controllers
{
    public class MusicController : Controller
    {
        MusicApiController objMusicApi = new MusicApiController();

        // GET: login
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string Username, string Password)
        {            
            bool isExists = objMusicApi.isUserExists(Username,Password);

            if (isExists) {
                System.Web.HttpContext.Current.Session["Username"] = Username;
                ViewData["Username"] = System.Web.HttpContext.Current.Session["Username"].ToString();
                return View("LocalSearch");
            }

            @ViewBag.error = "Username or Password is wrong.";
            return View();            
        }

        [HttpGet]
        public ActionResult Register()
        {            
            return View();
        }

        [HttpPost]
        public ActionResult Register(string Username, string Password)
        {            
            bool isExists = objMusicApi.isUserExists(Username, Password);

            if (!isExists)
            {
                bool isSuccess = objMusicApi.registerUser(Username, Password);

                if (isSuccess)
                {
                    System.Web.HttpContext.Current.Session["Username"] = Username;
                    ViewData["Username"] = System.Web.HttpContext.Current.Session["Username"].ToString();
                    return View("LocalSearch");
                }
                else                
                    @ViewBag.error = "Internal error occurred..";
            }
            else
                @ViewBag.error = "Username already exists.";

            return View();
        }

        public ActionResult GoogleSearch()
        {
            if (System.Web.HttpContext.Current.Session["Username"].ToString() == "")
                return View("Login");

            ViewData["Username"] = System.Web.HttpContext.Current.Session["Username"].ToString();
            return View();
        }

        [HttpGet]
        public ActionResult LocalSearch()
        {
            if (System.Web.HttpContext.Current.Session["Username"].ToString() == "")
                return View("Login");

            ViewData["Username"] = System.Web.HttpContext.Current.Session["Username"].ToString();
            return View();
        }

        [HttpPost]
        public JsonResult LocalSearch(string searchString, string optionString)
        {
            if (System.Web.HttpContext.Current.Session["Username"].ToString() == "")
                RedirectToAction("Login");

            ViewData["Username"] = System.Web.HttpContext.Current.Session["Username"].ToString();
            List<string> results = new List<string>();

            if (searchString != null) { 
                results = objMusicApi.searchString(searchString, optionString);
            }
            return Json(results, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult MyHistory()
        {
            if (System.Web.HttpContext.Current.Session["Username"].ToString() == "")
                return View("Login");

            string username = System.Web.HttpContext.Current.Session["Username"].ToString();
            ViewData["Username"] = username;

            int userid = objMusicApi.getUserIdByUsername(username);
            List<MusicViewModel> lstMusicVwMdl = objMusicApi.searchHistory(userid);

            return View(lstMusicVwMdl);
        }

        [HttpPost]
        public JsonResult MyHistory(string username, string track, string album, string artist)
        {
            bool isSuccessful = false;
            int user_id = objMusicApi.getUserIdByUsername(username);
            isSuccessful = objMusicApi.saveHistory(user_id, track, album, artist);
            return Json( isSuccessful , JsonRequestBehavior.AllowGet);
        }

        public ActionResult Logoff()
        {
            System.Web.HttpContext.Current.Session["Username"] = "";
            return View("Login");
        }
        
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Music Store", "LocalSearch", "Music", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("History", "MyHistory", "Music")</li>
                    <li>@Html.ActionLink("Local Search", "LocalSearch", "Music")</li>
                    <li>@Html.ActionLink("Google Search", "GoogleSearch", "Music")</li>
                    <li>@Html.ActionLink("Log Off", "Logoff", "Music")</li>
                </ul>
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Music Store</p>
        </footer>
    </div>
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_NewLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Music Store", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @*<ul class="nav navbar-nav">
                    <li>@Html.ActionLink("History", "MyHistory", "Music")</li>
                    <li>@Html.ActionLink("Local Search", "LocalSearch", "Music")</li>
                    <li>@Html.ActionLink("Google Search", "GoogleSearch", "Music")</li>
                </ul>*@
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Music Store</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>